### ISSUE TITLE
Unable to compile in Arduino IDE to J...543R board.

### ISSUE THREAD

**Issue by CoolmdXi** [calint/arduino-bam#1]
I was trying to comile your sketch to The JC827W543R board with Arduino but get the following compile error.

C:\Users\user\Documents\Arduino\sketches\CALINT\arduino-bam\bam\bam.ino: In function 'void render(int, int)':
C:\Users\user\Documents\Arduino\sketches\CALINT\arduino-bam\bam\bam.ino:371:25: error: 'class Arduino_ESP32QSPI' has no member named 'asyncDMAIsBusy'
  371 |         dma_busy += bus.asyncDMAIsBusy() ? 1 : 0;
      |                         ^~~~~~~~~~~~~~
C:\Users\user\Documents\Arduino\sketches\CALINT\arduino-bam\bam\bam.ino:372:13: error: 'class Arduino_ESP32QSPI' has no member named 'asyncDMAWriteBytes'
  372 |         bus.asyncDMAWriteBytes(
      |             ^~~~~~~~~~~~~~~~~~
C:\Users\user\Documents\Arduino\sketches\CALINT\arduino-bam\bam\bam.ino:393:21: error: 'class Arduino_ESP32QSPI' has no member named 'asyncDMAIsBusy'
  393 |     dma_busy += bus.asyncDMAIsBusy() ? 1 : 0;
      |                     ^~~~~~~~~~~~~~
C:\Users\user\Documents\Arduino\sketches\CALINT\arduino-bam\bam\bam.ino:394:9: error: 'class Arduino_ESP32QSPI' has no member named 'asyncDMAWriteBytes'
  394 |     bus.asyncDMAWriteBytes(
      |         ^~~~~~~~~~~~~~~~~~

exit status 1

Compilation error: 'class Arduino_ESP32QSPI' has no member named 'asyncDMAIsBusy'

I am quite new to this world and have little knowledge, so I was wondering if you had any Idea?
Kind regards and Thanks
Coolmd
PS have seen you in discord talking to Larry etc

**Comment by calint** [comment]
The project was mainly a demo for the author of `Arduino_GFX` with the proposed additions. The pull request was denied so the project is discontinued.

In the project there is a `libraries` folder with a forked version of `Arduino_GFX`. That version contains the functions that the compiler errors about.

Somewhere in Preferences you can specify the workspace to the root of the project and then it will compile the libraries provided in the `libraries` folder.

See `https://github.com/calint/platformio-bam` instead because it is the mainline for that project. It is for PlatformIO though.

Kind regards

**Comment by CoolmdXi** [comment]
Dear Calint,
Thanks for the swift response and for clearing up my concerns.
I am very new to this and have not ventured down the path of platform Io. I am struggling enough with Arduino Ide.
Thanks for youe advice and prompt attention
Regards
Coolmd

**Comment by calint** [comment]
You are welcome.

The README.md of the project indicates how to configure Arduino preferences for the project to compile.
